---
abstract: 'Perl Interface for github.com'
author:
  - 'Fayland Lam, C<< <fayland at gmail.com> >>'
  - 'Fayland Lam <fayland@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-GitHub
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  HTTP::Request: 0
  JSON::Any: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  MIME::Base64: 0
  Moo: 0
  Types::Standard: 0
  URI: 0
  URI::Escape: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/fayland/perl-net-github
version: 0.68
