---
abstract: 'Perl Interface for github.com'
author:
  - 'Fayland Lam, C<< <fayland at gmail.com> >>'
  - 'Fayland Lam <fayland@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Slurp: 0
  Test::MockModule: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-GitHub
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Any::Moose: 0
  Crypt::SSLeay: 0
  HTML::TreeBuilder: 0
  HTTP::Request::Common: 0
  JSON::Any: 0
  MIME::Base64: 0
  URI::Escape: 0
  WWW::Mechanize::GZip: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/fayland/perl-net-github/tree/master
version: 0.28
