---
abstract: 'Perl Interface for github.com'
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires:
  File::Slurp: 0
  Test::MockModule: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.790'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-GitHub
no_index:
  directory:
    - inc
    - t
requires:
  Crypt::SSLeay: 0
  Data::Dumper: 0
  JSON::Any: 0
  Moose: 0.57
  URI::Escape: 0
  WWW::Mechanize: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
